#Sistema di raccomandazione
Il sistema implementa un approccio di raccomandazione one-time, evitando la costruzione di matrici di similarità NxN. Applica un filtro hard sulla categoria e combina una similarità basata su ingredienti con una funzione deterministica di brand e segmento, pesate rispettivamente 0.8 e 0.2.

In [26]:
import pandas as pd
import numpy as np

1) Importo il df e creo un nuovo df con le colonne d'interesse

In [27]:
df = pd.read_csv("brand_categoria.csv",dtype={"code": str})

df = df[['code', 'product_name','brand_name', 'brand_segment','macro_category']].copy()
df['code'] = df['code'].astype(str)
df['product_name'] = df['product_name'].astype(str)
df['brand_name'] = df['brand_name'].astype(str)
df['brand_segment'] = df['brand_segment'].astype(str)
df['macro_category'] = df['macro_category'].astype(str)


df.tail(30)

,code,product_name,brand_name,brand_segment,macro_category
31026,5901887010371,eye make up remover,ziaja,middle,Makeup
31027,5901887010173,crema facial pepino,ziaja,middle,Face_Care
31028,5901887001348,gel limpiador de aceite de oliva,ziaja,middle,Oils
31029,5901887016953,crema facial ultra ligera aceite de oliva,ziaja,middle,Face_Care
31030,5901887008460,hand cream,ziaja,middle,Face_Care
31031,5901887006916,sensitive soothing day cream,ziaja,middle,Face_Care
31032,3700436313589,bush magic,zingus,mass_market,Other
31033,7596211001033,crema hidratante dia fps 15,zoah,mass_market,Face_Care
31034,7596211000203,crema corporal para la celulitis,zoah,mass_market,Body_Care
31035,4770161103723,balksvuju gyslociu luobeles,zolynelis,mass_market,Other
31036,8809576260489,zombie beauty,zombie beauty,mass_market,Other
31037,6132262400046,creme hydratante visage,zorah,mass_market,Face_Care
31038,7790990002278,jabon en polvo ropa,zorro,mass_market,Other
31039,7501026005985,jabon zote rosa,zote,mass_market,Other
31040,7501026005374,jabon zote blanco,zote,mass_market,Other
31041,0765011053420,zoya nail polish,zoya,mass_market,Nails
31042,6941349342670,crystal lip mask,zozu stanolant,mass_market,Makeup
31043,80000000286790,boom,zudio,mass_market,Other
31044,80000000173145,shower grl,zudio,mass_market,Body_Care
31045,80000000256654,sheet mask,zudio,mass_market,Masks
31046,1237654876548,pure petroleum jelly clasica,zurly,mass_market,Other
31047,1237654876838,cocoa petroleum jelly clasica,zurly,mass_market,Other
31048,8712561632065,zwitsal talkpoeder,zwitsal,mass_market,Other
31049,8720181147418,zwitsal,zwitsal,mass_market,Other
31050,8717163782002,zwitsal bodylotion,zwitsal,mass_market,Body_Care
31051,8717163769256,zachte creme,zwitsal,mass_market,Face_Care
31052,8712561405737,baby shampoo,zwitsal,mass_market,Hair_Care
31053,7311250044403,08sep2025,zyn,mass_market,Other
31054,8422829472004,locion antipiojos,zz,mass_market,Eye_Care
31055,8001841491165,complement alimentaire avec melatonine vitamin...,zzzquil sommeil,mass_market,Men_Care

In [28]:
df_ing = pd.read_csv("ingr_cat.csv",dtype={"code": str})


df_ing['code'] = df_ing['code'].astype(str)
df_ing['product_name'] = df_ing['product_name'].astype(str)
df_ing['macro_category'] = df_ing['macro_category'].astype(str)
df_ing['inci_name'] = df_ing['inci_name'].astype(str)

df_finale = (
    df_ing
    .groupby(['code', 'product_name', 'macro_category'])['inci_name']
    .apply(lambda lst: ", ".join(sorted(set(lst))))
    .reset_index()
    .rename(columns={'inci_name': 'ingredients'}))

df_finale.tail(20)

,code,product_name,macro_category,ingredients
15111,96121214,Powder soft anti perspirant,Other,"Alpha-Isomethyl Lonone, Aluminum Zirconium Tet..."
15112,96125694,REXONA Déodorant Homme Bille Anti Transpirant ...,Deodorants,"Alpha-Isomethyl Ionone, Aluminum Zirconium Tet..."
15113,96125748,Motionsense active shield,Other,"Alpha-Lsomethyl Lonone, Aluminum Chlorohydrate..."
15114,96130339,Dove zero original 50ml,Body_Care,"Alpha-Isomethyl Ionone, Benzyl Alcohol, Citric..."
15115,96132289,Axe Déodorant Anti Bactérien You Spray 100ml,Deodorants,"Alcohol Denat, Alpha-Isomethyl Ionone, Butane,..."
15116,96132876,Monsavon Déodorant Femme Spray Compressé Fleur...,Hygiene,"Alpha-Isomethyl Ionone, Benzyl Alcohol, Bht, B..."
15117,96132906,Monsavon Déodorant Femme Spray Compressé Grena...,Hygiene,"Alpha-Isomethyl Ionone, Benzyl Alcohol, Bht, B..."
15118,96134696,DOVE Déodorant Femme Spray Compressé Pierre d'...,Body_Care,"Alpha-Isomethyl Ionone, Benzyl Alcohol, Benzyl..."
15119,96148402,Monsavon Déodorant Femme Spray Compressé Vanil...,Hygiene,"Benzyl Alcohol, Bht, Butane, Butyrospermum Par..."
15120,96183281,sensodyne,Other,"Aroma, Carbomer, Cocamidopropyl Betaine, Die 7..."
15121,96190807,Clay Pomade,Other,"Bentonite, Ceteareth-20, Ethylhexyl Palmitate,..."
15122,9680150153491,nutri-extrême richesse,Other,"Alpha-Isomethyl Ionone, Benzyl Alcohol, Benzyl..."
15123,9700490730098,Allo,Other,Allo
15124,9767014005810,prêt plus,Other,"91717 Wassertruedingen, Water"
15125,9782253122111,Doliprane bebe,Makeup,"Acide Citrique Anhydre, Arme Orange, Arme Pch ..."
15126,9836763040011,Fragrance Free Conditioner,Hair_Care,"Behentrimonium Chloride, Cetearyl Alcohol, Cet..."
15127,9858406315515,Colgate plax,Hygiene,Colgate
15128,988010630504861790,curl therapy conditioner wash,Hair_Care,"Bambusa Vulgaris Shoot Extract, Capryliccapric..."
15129,9978135848778,Pigmento,Men_Care,"Decamethylcyclopentasiloxane, Ethylhexyl Palmi..."
15130,99941208,Zincodermil shampoo,Hair_Care,"20, Arctium Lappa Root Extract, Citric Acid, C..."

In [29]:
#per la semplificazione della ricerca in fase di test, è una lista di "code" in comune tra i dataset
common_codes = set(df['code']).intersection(set(df_finale['code']))

print(f"Prodotti in df: {len(df)}")
print(f"Prodotti in df_finale: {len(df_finale)}")
print(f"Prodotti comuni: {len(common_codes)}")
common_codes

Prodotti in df: 31056
Prodotti in df_finale: 15131
Prodotti comuni: 12304

{'1237654876548',
 '0735303504312',
 '8431876282177',
 '3593290031993',
 '3596209937119',
 '3380390900904',
 '4337256573030',
 '3600541072992',
 '7790740508401',
 '0651986800216',
 '3596710524129',
 '8712561535243',
 '8004020931766',
 '4311501066409',
 '3250391571642',
 '8710447365724',
 '7501026011511',
 '3282770154559',
 '3282779363815',
 '8710522378564',
 '4311596019427',
 '8710447349960',
 '42345060',
 '3489940081084',
 '3517360018288',
 '3251248046047',
 '3574661091020',
 '8851515605974',
 '3468080145047',
 '3600523279319',
 '3600541540262',
 '3181730125007',
 '0764302290629',
 '3549620007602',
 '3574661002378',
 '3700992600048',
 '4005900035622',
 '3760177361607',
 '3517360010572',
 '3760179070262',
 '0810112515848',
 '0761571362200',
 '5022496101301',
 '3600550284256',
 '3245678562277',
 '7899706192712',
 '4066447106275',
 '4010355296306',
 '7046110066775',
 '20527310',
 '7702018366200',
 '4005808484843',
 '8480017839824',
 '3574661464978',
 '0769915152203',
 '3661596986436',
 '8710522707579',
 '3245678629888',
 '4066447231250',
 '3141380042536',
 '3245678689493',
 '3346029401808',
 '3770002587027',
 '9313880201001',
 '3461922010206',
 '3700076443998',
 '0816645023966',
 '8410412020299',
 '3560070923250',
 '4005900879561',
 '8710522385883',
 '4084500087378',
 '8431876271744',
 '3549620005028',
 '43437382',
 '3401360266759',
 '3401566677519',
 '4021457615278',
 '4260758481841',
 '3700276346280',
 '3517360016161',
 '3600531379254',
 '3660005663180',
 '3245677725475',
 '4305615827469',
 '9333441008450',
 '3504105029951',
 '3600523881598',
 '3600541883642',
 '4008233132945',
 '3600550560077',
 '5054563104328',
 '80775010',
 '8850006306468',
 '3600542372398',
 '8710522470572',
 '8901138847920',
 '3256220856126',
 '4021457645084',
 '4015100292022',
 '4061461592806',
 '3600531629106',
 '8004608283591',
 '6939293513246',
 '3600523971350',
 '9088882463886',
 '3050070007468',
 '3245678612569',
 '4607945640399',
 '3600523409273',
 '4056489235088',
 '3245678709085',
 '9005835312671',
 '3181730332221',
 '3596710516582',
 '3245678042182',
 '4058172336317',
 '7340011429234',
 '3245678132005',
 '3600550254211',
 '7310610021269',
 '3560070784608',
 '8710447382042',
 '4005808661411',
 '7332531042031',
 '8712561484121',
 '8029408008076',
 '4005900699008',
 '3614222677789',
 '8809479166444',
 '5025452000601',
 '3600542368810',
 '8710522329894',
 '4084500979208',
 '8717163798003',
 '4005900122063',
 '3125300000042',
 '4005900127525',
 '5000174118452',
 '7640183490262',
 '8161351759015',
 '8699943340247',
 '8710447276600',
 '9009827000560',
 '4305615610030',
 '91313441',
 '3140100143065',
 '4010355347329',
 '8005892347020',
 '4036221432302',
 '8710198346157',
 '4582469490807',
 '3264680010330',
 '3596710542239',
 '3600550454055',
 '3660005251530',
 '3770000717006',
 '3549620033007',
 '3574661320700',
 '8720908031129',
 '30070349',
 '3596710517015',
 '3600550944365',
 '42449126',
 '3600523216253',
 '3245678152539',
 '3600521248393',
 '3600522405115',
 '04804505',
 '8718906909007',
 '8718951419902',
 '8710908437137',
 '8710847998577',
 '4010355197948',
 '3282779007603',
 '8720181397400',
 '3504105029920',
 '3250392228415',
 '3760346073928',
 '8718114148304',
 '7891024128992',
 '3770000717037',
 '3600550261486',
 '2000000000894',
 '4008455308210',
 '0792850336995',
 '4005900134264',
 '3401564695546',
 '3178041308793',
 '3662076001243',
 '3380380072710',
 '7630028631127',
 '0854620008034',
 '3574661151250',
 '7506078972292',
 '8710447284117',
 '0738678239940',
 '3433422404397',
 '2000000003669',
 '8402001011801',
 '3596710381289',
 '3760214630017',
 '3537090016859',
 '8718951658691',
 '3058325067427',
 '8717644434758',
 '4005808395330',
 '3770000717587',
 '3574661186276',
 '3504105002916',
 '6928001831741',
 '0812154030112',
 '3574661554280',
 '1468488405721',
 '3564700718513',
 '3346470612020',
 '4005900107305',
 '3600550817140',
 '3286010008985',
 '8901030873218',
 '2000000005165',
 '3600542009966',
 '4010355559036',
 '3517360021509',
 '8717163690277',
 '3401360192546',
 '5420073400098',
 '3564700799451',
 '3600550260267',
 '5038483431542',
 '5765228837931',
 '3250391645206',
 '3401577538663',
 '3600530659661',
 '5060144647795',
 '3468080009028',
 '5201279020798',
 '8714789895536',
 '3464660002007',
 '4260698970771',
 '5028197252472',
 '4061462227479',
 '4063367400872',
 '4084500998827',
 '8901088064576',
 '96111741',
 '8720181029233',
 '59013648',
 '3058325505400',
 '3600523192977',
 '2000000152565',
 '3596710324354',
 '4056489526728',
 '8710908858567',
 '3282770037753',
 '3574661133102',
 '3600523443970',
 '3760209870121',
 '3700172700179',
 '5055170281013',
 '3660005306636',
 '3222475305191',
 '3600523827763',
 '3052503531281',
 '3450970129527',
 '4020829009240',
 '8711700917773',
 '7032069717455',
 '4017645038318',
 '3245678629895',
 '3286011059702',
 '3564700726709',
 '4305615623177',
 '8901138511784',
 '3606000537439',
 '3430750793537',
 '8422385299756',
 '4005900363879',
 '3468080101210',
 '3337872411809',
 '3337871321888',
 '4015400932161',
 '8714789880525',
 '4104260064539',
 '0817939018590',
 '8712561715508',
 '0773602048717',
 '5028197823160',
 '5410076932535',
 '9331137019216',
 '3517360003239',
 '8431876271706',
 '8718951068414',
 '3273818822660',
 '8480000467423',
 '8411126020674',
 '3700426220651',
 '3960640000167',
 '8906015580402',
 '3770002153178',
 '7502212297931',
 '4084500488465',
 '59083146',
 '8710522942840',
 '3215666800018',
 '3612060006785',
 '59019107',
 '6920354822209',
 '3094905001405',
 '3760141130734',
 '3401353741591',
 '3596200081309',
 '4305615629223',
 '0724742003708',
 '3517360013856',
 '8714789913940',
 '3245678042151',
 '3248140657518',
 '4007547301870',
 '3616303440558',
 '30176188',
 '8710847969737',
 '0810171573148',
 '8992727003858',
 '3346470611733',
 '8806164115985',
 '3257984186634',
 '3282779327084',
 '3600541791916',
 '3401363628561',
 '5021320041219',
 '0737052351100',
 '3600550049336',
 '8001280022036',
 '3560070883325',
 '80849483',
 '3286010012449',
 '8718114060194',
 '3245678042229',
 '3178040699021',
 '4045612002611',
 '3282779374620',
 '8720181029240',
 '3600523939763',
 '3251248032606',
 '3560070917488',
 '8435268322939',
 '8025796001934',
 '0895499714305',
 '3517360014181',
 '3574660724257',
 '8436097095735',
 '8710537040166',
 '3058320042061',
 '3466761831531',
 '0732913229307',
 '8431876275216',
 '3153716003432',
 '4005808707539',
 '0816218026110',
 '8906157900762',
 '4056489749394',
 '4005900957726',
 '3256224363293',
 '5906439040066',
 '0821055050297',
 '8718951186897',
 '8054615474024',
 '8714789554792',
 '4690471126581',
 '3770002239063',
 '8714789862057',
 '20072339',
 '3450970024600',
 '3250391896493',
 '3560070784639',
 '3596710516957',
 '9358741475252',
 '6281001113058',
 '8711700963503',
 '0835374001144',
 '3600521987711',
 '3251241042053',
 '3760354680101',
 '3600530625987',
 '3489941049113',
 '8710908585791',
 '7310610022655',
 '2000000003489',
 '3133200053129',
 '7614700005239',
 '73123538',
 '2000000002886',
 '3474393019470',
 '87343601',
 '7899706172745',
 '8431876272239',
 '2000000005172',
 '7750045390187',
 '3600522054085',
 '8001280068072',
 '8022328111116',
 '3600531579456',
 '4059729446992',
 '3337871328337',
 '3593290021895',
 '7898623951785',
 '3257981609006',
 '4005370001004',
 '3760099592424',
 '3517360010558',
 '3760099594343',
 '4607034470708',
 '3245678704646',
 '8710522570692',
 '4010355322852',
 '4024144623938',
 '80063735',
 '3251241025629',
 '3284410026158',
 '3560070623693',
 '3600531369484',
 '8410436463355',
 '8710522605530',
 '8719668020245',
 '3245678159989',
 '3564700561140',
 '3518646027536',
 '8480000420947',
 '42269670',
 '8717163607268',
 '20172756',
 '3760016580978',
 '3282770142112',
 '8480000468086',
 '8009518198317',
 '3600550564099',
 '3058325689322',
 '3337875763790',
 '5054563193445',
 '3600542130790',
 '3282779359184',
 '8001090101341',
 '5029053550237',
 '7896085873270',
 '3450601029011',
 '3401560081800',
 '8410412029919',
 '8006540367490',
 '8717644256152',
 '5997001738986',
 '3574661285894',
 '3574661151267',
 '3337871323820',
 '3378872108207',
 '3600540542069',
 '3700445920020',
 '3574661309637',
 '3596710399451',
 '3600541875227',
 '5400247031846',
 '8720181331244',
 '3700601100891',
 '3760099593377',
 '7640183490859',
 '3401578379715',
 '3468080001718',
 '3800038932369',
 '8431876238082',
 '3661434000720',
 '4005900053596',
 '96091159',
 '4305615572901',
 '2000000003487',
 '1002003038089',
 '59083139',
 '8710908548512',
 '8712561480369',
 '3263855948935',
 '3256222740607',
 '4066447331202',
 '3560070902705',
 '3450601032417',
 '8001090047014',
 '8432225096735',
 '3401399277382',
 '3600541288560',
 '7611916157257',
 '4305615842424',
 '8431876279610',
 '4005800266089',
 '3331840550002',
 '42424536',
 '8700216203760',
 '8711700543613',
 '3517360001822',
 '3245678044483',
 '0745114958068',
 '8711600504141',
 '4005808170005',
 '4021457614134',
 '3263855907826',
 '8000137018086',
 '8718951131767',
 '0810095597954',
 '2000000004330',
 '3600523718269',
 '3245678134139',
 '4008617005001',
 '3560070611423',
 '20250898',
 '3245678691472',
 '8029408021747',
 '3660005760711',
 '3770018286150',
 '6411000594002',
 '5054563023452',
 '8712561772730',
 '8717163661574',
 '4010355505347',
 '3263855988818',
 '8480000468161',
 '0634707505546',
 '8809427864293',
 '0650240013881',
 '7501026007101',
 '8901030868719',
 '3600521390535',
 '0850042058282',
 '9556589003303',
 '3489940070569',
 '4006000037660',
 '8700216449632',
 '8021983810921',
 '3600530746538',
 '3600542520263',
 '5902686254331',
 '3504105025342',
 '8901571010844',
 '0827854007234',
 '8001120834102',
 '3600523214938',
 '5011842107128',
 '3596710534807',
 '2000000002887',
 '7035620021466',
 '9312657110294',
 '3661467002128',
 '8001090047342',
 '6006174010559',
 '3596710524082',
 '3224055850442',
 '3600521730645',
 '8720181042638',
 '3159870466212',
 '0810095596261',
 '3661500521975',
 '3574660296013',
 '4001499957482',
 '7613356176102',
 '3401397675883',
 '12310784',
 '3348901563635',
 '3245678627136',
 '42419976',
 '7775005010257',
 '3607345216713',
 '3378872073703',
 '3700392166410',
 '8001280068003',
 '8718951007222',
 '8480000608420',
 '7509546652054',
 '7640168931247',
 '5013692226998',
 '5033102916523',
 '7877771368461',
 '3256224064565',
 '3600550580051',
 '8431876273472',
 '8710908830174',
 '5400141700244',
 '8001090223654',
 '8717163962084',
 '3251241047676',
 '4058172702013',
 '3245678691502',
 '20968632',
 '8004608236580',
 '3574661169392',
 '3700763501581',
 '3346029200296',
 '8710847952869',
 '3474630644786',
 '8431876266375',
 '60018960',
 '9347108004884',
 '8710522487334',
 '0813424022851',
 '8904109498923',
 '3660005338682',
 '3504105028374',
 '8431876279573',
 '4305615915333',
 '3574661711485',
 '96100554',
 '8710522469965',
 '8718951075733',
 '3182612705119',
 '3600531632427',
 '3178040674585',
 '7702018015665',
 '6118000041252',
 '8480000467874',
 '3178040334229',
 '4809016116097',
 '4902430333597',
 '8712566550159',
 '3596710534777',
 '3596710534821',
 '3595890240287',
 '4061458121422',
 '20553531',
 '2000000002894',
 '1748567444460',
 '4388844092402',
 '6134606000059',
 '7891010253936',
 '9100000706924',
 '7891010669843',
 '3450970118811',
 '7640175610081',
 '29023295',
 '8001120704788',
 '10191959',
 '3600541177741',
 '8720181192098',
 '8697926007439',
 '3596710521692',
 '3596710517282',
 '8717163924167',
 '3596710517138',
 '6132262400046',
 '8700216667265',
 '30096639',
 '3282779027540',
 '3348901330572',
 '3600523755271',
 '8710447363812',
 '8711600937727',
 '4021457637591',
 '20525101',
 '3574661065335',
 '8714789119564',
 '4065331001542',
 '2000000001061',
 '2900011800034',
 '3537090018129',
 '4047196040775',
 '8711600458758',
 '3600542326452',
 '3600541696495',
 '3504108010574',
 '3517360006278',
 '3600523971336',
 '4015100212617',
 '3450601040153',
 '4015001007428',
 '5907502687898',
 '3282770072778',
 '3660005238234',
 '6920354821660',
 '7899852025551',
 '3595899646028',
 '3607340668258',
 '4005900475039',
 '0730852167094',
 '4005808255788',
 '0884486329912',
 '4305615573915',
 '0819793010291',
 '4029811145751',
 '3662217005147',
 '8003520013064',
 '3337875588621',
 '8721073610492',
 '8720181086281',
 '3178041321648',
 '0769915193954',
 '8710522470022',
 '3245678127438',
 '8710522644010',
 '8718951242722',
 '3245678089668',
 '3181730199978',
 '20036218',
 '3298651711360',
 '2200031373380',
 '3600540881663',
 '0666151010673',
 '3595890243462',
 '8006540786116',
 '3329310025983',
 '4021354033571',
 '8710908587948',
 '0752830779389',
 '3380380083372',
 '3518646023118',
 '3596710524099',
 '7332531093965',
 '3701129802076',
 '7798175712332',
 '8001090181015',
 '3596710521593',
 '3614272080416',
 '8809255781908',
 '3504105028404',
 '3140100320978',
 '3760269130074',
 '8720181419126',
 '3600541237827',
 '75027537',
 '0717334221499',
 '4000196031976',
 '8718951137530',
 '3560070311453',
 '0880917938852',
 '3614271993007',
 '3245678599976',
 '3504105028657',
 '3564700746851',
 '7899702302702',
 '3595890234552',
 '8710522646212',
 '8906058357580',
 '0800897181154',
 '3600522215370',
 '6955545460854',
 '3596710257249',
 '3564700560860',
 '3178040690912',
 '3600550812565',
 '3245677725369',
 '3600542470421',
 '0671635726599',
 '3450601026515',
 '0628467002711',
 '3564700714409',
 '3263855940830',
 '3600530588039',
 '3660005548890',
 '8712561657396',
 '0834576005875',
 '8720181721632',
 '3596710517213',
 '3350033437791',
 '3660005984537',
 '8016225353946',
 '3250391444175',
 '4104260041714',
 '9346627007093',
 '4059729341556',
 '8001841062754',
 '3182611231022',
 '8480000466990',
 '3522931031887',
 '30174115',
 '2050001419545',
 '2000000003493',
 '3596710524709',
 '3282770139204',
 '4005808183043',
 '0850003721378',
 '3283950924344',
 '3178040667044',
 '0884486462404',
 '08133025',
 '7899846023693',
 '3001000012502',
 '11287162',
 '08716491',
 '3337872414084',
 '5900652000340',
 '4005900491046',
 '4020829009110',
 '7790010570640',
 '8710447370094',
 '4005808751990',
 '0834639001004',
 '8710447381915',
 '4005900757968',
 '3286011059610',
 '3760375980006',
 '8700216412926',
 '2000000000050',
 '5410091718350',
 '3178040695153',
 '3760194657707',
 '3468080150157',
 '0856556004111',
 '3329310002120',
 '7702538111502',
 '4047400093801',
 '0850037549122',
 '3600551074337',
 '8691988010383',
 '8710522476086',
 '3770019886267',
 '0745114069962',
 '7332531093484',
 '8712561967037',
 '3700998201195',
 '8411047145012',
 '0763615672634',
 '8710522489796',
 '3600522497035',
 '3600550518030',
 '8710447388785',
 '5028197557904',
 '3700558600000',
 '9327693007071',
 '3600542015172',
 '7630028609348',
 '3574661048208',
 '0764302211068',
 '4311501666203',
 '4337256438131',
 '0811068019312',
 '2000000001073',
 '3178040643802',
 '3450601021855',
 '7501026009396',
 '3178041344258',
 '8718951185784',
 '8710522754726',
 '3511720117970',
 '4002448122432',
 '8720181131042',
 '0708002300363',
 '8480013686118',
 '3600523939817',
 '4058172458439',
 '5060686200113',
 '3574661687018',
 '3700743300234',
 '8700216421102',
 '8436575092362',
 '4005808515592',
 '6920354819667',
 '3600523586868',
 '3700502800425',
 '42419440',
 '3760091820242',
 '8480000443137',
 '0834893004049',
 '7313272139747',
 '3600531589462',
 '3350033673564',
 '3600541934047',
 '0808124111042',
 '59013976',
 '0810117031084',
 '7506306215764',
 '8711600462236',
 '8720181302046',
 '4005808890576',
 '6281001112013',
 '3600522992455',
 '8717524072445',
 '4001499946493',
 '8714789806013',
 '3346470610347',
 '4015000999922',
 '8411135483262',
 '3014230021589',
 '8903105032681',
 '4005808669707',
 '7891150054455',
 '4008890012024',
 '8717163668856',
 '8929991741728',
 '5704537200074',
 '80851226',
 '8480000226310',
 '3661434004582',
 '3663787551875',
 '3401396868613',
 '2004060008264',
 '3504105028718',
 '3564700569528',
 '3600520772035',
 '7611916001420',
 '7340011315599',
 '3606000607118',
 '8002140137105',
 '3600550564075',
 '3286010022097',
 '3245678599853',
 '3574661065359',
 '3564700864678',
 '2000000004888',
 '8001280400865',
 '8431876272208',
 '7640183490293',
 '8712561785457',
 '4061461592769',
 '4305615612393',
 '2000000000728',
 '8720254337098',
 '8720181001833',
 '9415991240174',
 '3661434000546',
 '3596710517077',
 '3264680007576',
 '3700376703013',
 '4770001002490',
 '8717163041550',
 '8717163947715',
 '5054563124395',
 '8410225509998',
 '8431876287653',
 '4036221600176',
 '3600522862703',
 '0681131175869',
 '0803954301038',
 '0810425035873',
 '4011700745135',
 '3094905000743',
 '3282779314350',
 '25928129',
 '3250392620844',
 '5060968411565',
 '8008277205083',
 '4005900777263',
 '0667888306824',
 '8691841307063',
 '8850006325216',
 '3245678127391',
 '6935743174876',
 '5054596164825',
 '3181730192627',
 '3414094185685',
 '8052862440090',
 '3284410014933',
 '8714789921006',
 '5601092010202',
 '3600531324902',
 '3245678691458',
 '3474637103576',
 '3596710520114',
 '3660992005314',
 '6036000010231',
 '7640183491177',
 '3504105017200',
 '5000101032905',
 '3564706581876',
 '8858890211219',
 '3256221661743',
 '5012254067680',
 '0616576127128',
 '3560070900336',
 '4010160005070',
 '5906395837137',
 '8431876248180',
 '0722510027000',
 '3380810040463',
 '3600541805880',
 '8710847929083',
 '3564700750223',
 '8710522351840',
 '8001090101280',
 '3600523033942',
 '0885892654148',
 '3401528544910',
 '8710908586095',
 '3600523062713',
 '0724000593484',
 '8714789926292',
 '8710847998584',
 '5028197868918',
 '3600550582031',
 '3700914601962',
 '6937914925058',
 '4005808678747',
 '7509552910124',
 '3263855850597',
 '3760137430114',
 '3245678674888',
 '0863765000087',
 '3245678127360',
 '0641628501731',
 '8414719408125',
 '8710522579213',
 '3489940063073',
 '0810374027561',
 '8710604788816',
 '0843536107924',
 '4015100009590',
 '3140100394344',
 '3563210006028',
 ...}

**2. Assegnazione pesi ai brand_segment.**

Il sistema di suggerimento tiene conto del segmento di mercato e pesa la similarità in base ad esso.
Prodotti dello stesso segmento avranno peso maggiore.

In [30]:
SEGMENT_SIMILARITY = {
    ('middle', 'middle'): 0.7,
    ('mass_market', 'mass_market'): 0.7,
    ('luxury', 'luxury'): 0.7,

    ('mass_market', 'middle'): 0.5,
    ('middle', 'mass_market'): 0.5,

    ('mass_market', 'luxury'): 0.3,
    ('luxury', 'mass_market'): 0.3,

    ('middle', 'luxury'): 0.5,
    ('luxury', 'middle'): 0.5
}

**3. Creazione dell'array di similarità 1xK.**

Per il brand non uso una cosine similarity, ma una funzione deterministica basata su regole di business che tengono conto sia dell’identità del brand sia del segmento di mercato.

Il sistema applica un hard filter sulla categoria per ridurre lo spazio di ricerca e garantire coerenza semantica, e successivamente calcola una similarità pesata basata su ingredienti e su regole di brand e segmento.

In [31]:
def brand_segment_similarity_1xK(
    query_product_id,
    df,
    category_col='macro_category',
    segment_col='brand_segment'
):
    query_product_id = str(query_product_id)

    if query_product_id not in df['code'].values:
        raise ValueError("Codice prodotto non trovato")

    query_row = df[df['code'] == query_product_id].iloc[0]
    query_category = query_row[category_col]
    query_brand = query_row['brand_name']
    query_segment = query_row[segment_col]
    query_product_name = query_row['product_name']  # ← AGGIUNTA

    # Filtro hard: stessa categoria -> ricerca tra prodotti della stessa categoria
    df_filtered = df[df[category_col] == query_category].copy()
    df_filtered = df_filtered[df_filtered['code'] != query_product_id]
    #filtro per evitare che restituisca lo stesso prodotto
    df_filtered['query_brand_name'] = query_brand
    df_filtered['query_product_name'] = query_product_name

    similarities = []

    for _, row in df_filtered.iterrows():
        if row['brand_name'] == query_brand:
            similarities.append(1.0)#se il prodotto appartiene allo stesso brand avrà similarità massima
        else:
            pair = (query_segment, row[segment_col]) #altrimenti considera il segmento di mercato
            similarities.append(SEGMENT_SIMILARITY.get(pair, 0.0))
    df_filtered['similarity'] = similarities
    return np.array(similarities), df_filtered

4. Applicazione della funzione e creazione dell'aray one-time a partire dal prodotto

In [32]:
query_id = input('Inserisci il codice del prodotto: ')

brand_sim = brand_segment_similarity_1xK(query_id, df)
#non ottengo una matrice di similarità NXN, ma un array 1xK:
#cioè la similarità del prodotto query rispetto a tutti gli altri prodotti della stessa categoria



#brand_sim è una tupla: il primo elemento è l'array 1xK, il secondo elemento è il dataframe con i prodotti candidati
#brand_sim == (similarity_array, df_filtered).
#la tupla serve a sapere a quali prodotti mi riferisco
brand_sim_array, df_brand_candidates = brand_sim

In [33]:
brand_sim_array[:10] #vedo i primi dieci valori di similarità

array([0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7])

In [34]:
df_brand_candidates = df_brand_candidates[[
    'code',
    'query_product_name',
    'query_brand_name',
    'product_name',
    'brand_name',
    'brand_segment',
    'macro_category',
    'similarity'
]]

In [35]:
df_brand_candidates.sort_values('similarity', ascending= False).head(10) #vedo i primi dieci candidati

,code,query_product_name,query_brand_name,product_name,brand_name,brand_segment,macro_category,similarity
26172,5054563256522,sensodyne repair protect,sensodyne,sensodyne expert protect rapide action,sensodyne,mass_market,Other,1.0
26174,8710464140021,sensodyne repair protect,sensodyne,pro glasur,sensodyne,mass_market,Other,1.0
26158,7498100701454,sensodyne repair protect,sensodyne,repare et protege,sensodyne,mass_market,Other,1.0
26159,5054563185815,sensodyne repair protect,sensodyne,fresh mint,sensodyne,mass_market,Other,1.0
26160,5054563155658,sensodyne repair protect,sensodyne,repair protect,sensodyne,mass_market,Other,1.0
26162,5054563186249,sensodyne repair protect,sensodyne,zahnpasta,sensodyne,mass_market,Other,1.0
26165,5054563156594,sensodyne repair protect,sensodyne,rapid zahnpasta,sensodyne,mass_market,Other,1.0
26168,5054563206688,sensodyne repair protect,sensodyne,sensodyne soin gencives,sensodyne,mass_market,Other,1.0
26169,5054563209290,sensodyne repair protect,sensodyne,sensodyne proschmelz,sensodyne,mass_market,Other,1.0
26170,5054563210180,sensodyne repair protect,sensodyne,zahnpasta clinical repair,sensodyne,mass_market,Other,1.0

5. Con questa funzione si trovano i prodotti più simili a un prodotto dato, guardando solo gli ingredienti. Prima limita il confronto ai prodotti della stessa categoria, così il confronto ha senso.
Poi confronta gli ingredienti del prodotto scelto con quelli degli altri e dice quanto si assomigliano, usando un punteggio numerico.

In [36]:
#pulizia per esclusione ingredienti che potrebbero compromettere il corretto
#calcolo della similarità
EXCLUDE_INGREDIENTS = {
    'aqua', 'water', 'parfum', 'fragrance',
    'ci', 'color', 'colour',
    'sodium chloride'
}

def clean_ingredients(ing_string):
    ing = [
        i.strip().lower()
        for i in ing_string.split(',')
        if len(i.strip()) > 2
    ]
    ing = [
        i for i in ing
        if not any(x in i for x in EXCLUDE_INGREDIENTS)
        and not i.startswith('ci ')
    ]
    return list(set(ing))

In [37]:
df_finale['ingredients_list'] = df_finale['ingredients'].apply(clean_ingredients)

df_finale[['ingredients', 'ingredients_list']].head(10)

,ingredients,ingredients_list
0,"Arnica Montana, Avoid Contact With Eyes, Burit...","[tocopherol, buriti oil, menthol, silicones, a..."
1,Oil,[oil]
2,"Added Sugarss, Colorings, Cr 6Ad, Croydon, Lac...","[lactose, cr 6ad, croydon, preservatives, adde..."
3,Oil,[oil]
4,"Lilium Candidum Flower Extract, Oil","[lilium candidum flower extract, oil]"
5,"Allantoin, Aloe Barbadensis Leaf Juice, Benzoi...","[allantoin, glycerin, aloe barbadensis leaf ju..."
6,"Coco-Glucoside, Decyl Glucoside, Glycerin, Gly...","[leuconostocradish root ferment filtrate, glyc..."
7,Lawsonia Inermis Leaf Powder,[lawsonia inermis leaf powder]
8,Natural Calcium Bentonite Clay,[]
9,"Cellulose Gum, Citric Acid, Cocamidopropyl Bet...","[sodium saccharin, glycerin, titanium dioxide,..."

In [38]:
def jaccard_similarity(set_a, set_b):
    if not set_a or not set_b:
        return 0.0
    return len(set_a & set_b) / len(set_a | set_b)

In [39]:
def ingredient_similarity_1xK(
    query_product_id,
    df_finale,
    category_col='macro_category'
):
    query_product_id = str(query_product_id)

    if query_product_id not in df_finale['code'].values:
        raise ValueError("Codice prodotto non trovato")

    query_row = df_finale[df_finale['code'] == query_product_id].iloc[0]
    query_category = query_row[category_col]
    query_ing = set(query_row['ingredients_list'])

    # Filtro hard: stessa categoria
    df_filtered = df_finale[df_finale[category_col] == query_category].copy()
    df_filtered = df_filtered[df_filtered['code'] != query_product_id]



    print(f"Trovati {len(df_filtered)} prodotti nella stessa categoria")

    similarities = []

    for _, row in df_filtered.iterrows():
        sim = jaccard_similarity(
            query_ing,
            set(row['ingredients_list'])
        )
        similarities.append(sim)

    return np.array(similarities), df_filtered

In [40]:
ing_sim_array, df_ing_candidates = ingredient_similarity_1xK(query_id, df_finale)

ing_sim_array[:10]

Trovati 5582 prodotti nella stessa categoria

array([0.        , 0.        , 0.0625    , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.04166667, 0.05263158])

In [41]:
#aggiunta similarità e is_query per vedere quali sono i prod raccomandati e
#qual è il prodotto originale cercato
df_ing_candidates_temp = df_ing_candidates[df_ing_candidates['code'] != query_id].copy()
df_ing_candidates_temp['ing_sim'] = ing_sim_array
df_ing_candidates_temp['is_query'] = False
df_ing_candidates_temp = df_ing_candidates_temp.sort_values(by='ing_sim', ascending=False).reset_index(drop=True)


df_query_ing = df_finale[df_finale['code'] == query_id].copy()
df_query_ing['ing_sim'] = 1.0        # similarità massima con se stesso
df_query_ing['is_query'] = True

df_ing_candidates = pd.concat(
    [df_query_ing, df_ing_candidates_temp],
    ignore_index=True
)

df_ing_candidates.head(10)

,code,product_name,macro_category,ingredients,ingredients_list,ing_sim,is_query
0,8901571010844,Sensodyne Repair & Protect,Other,"Aroma, Calcium Sodium Phosphosilicate, Carbome...","[aroma, sodium saccharin, carbomer, glycerin, ...",1.000000,True
1,3094905000033,Répare & Protège,Other,"Aroma, Calcium Sodium Phosphosilicate, Carbome...","[aroma, sodium saccharin, carbomer, glycerin, ...",0.916667,False
2,5054563155658,Repair & Protect,Other,"Aroma, Calcium Sodium Phosphosilicate, Carbome...","[aroma, sodium saccharin, carbomer, glycerin, ...",0.916667,False
3,5054563006592,Sensodyne repair & protect,Other,"Aroma, Calcium Sodium Phosphosilicate, Carbome...","[aroma, sodium saccharin, carbomer, glycerin, ...",0.916667,False
4,6001076192525,tooth,Other,"Aroma, Calcium Sodium Phosphosilicate, Carbome...","[aroma, sodium saccharin, contains sodium fluo...",0.846154,False
5,5054563109743,Sensodyne sensibilidade e gengivas,Other,"Aroma, Carbomer, Cocamidopropyl Betaine, Glyce...","[aroma, sodium saccharin, carbomer, glycerin, ...",0.733333,False
6,5054563010278,Rapide Action Extra Fresh,Other,"Aroma, Carbomer, Cocamidopropyl Betaine, Glyce...","[aroma, sodium saccharin, carbomer, glycerin, ...",0.666667,False
7,05050499,Sensodyne Sensibilité & Gencives,Other,"Aroma, Carbomer, Cocamidopropyl Betaine, Glyce...","[aroma, sodium saccharin, carbomer, glycerin, ...",0.666667,False
8,5054563024558,Rapide Action,Other,"Aroma, Carbomer, Cocamidopropyl Betaine, Glyce...","[aroma, sodium saccharin, carbomer, glycerin, ...",0.600000,False
9,3094904751622,Rapide action,Other,"Aroma, Carbomer, Cocamidopropyl Betaine, Glyce...","[aroma, sodium saccharin, carbomer, glycerin, ...",0.600000,False

In [42]:
query_product_ingredients = set(
    df_finale[df_finale['code'] == query_id]['ingredients_list'].iloc[0]
)

def get_common_ingredients(candidate_ingredients):
    return list(query_product_ingredients.intersection(set(candidate_ingredients)))

df_ing_candidates['common_ingr'] = df_ing_candidates['ingredients_list'].apply(get_common_ingredients)

df_ing_candidates[['code', 'product_name', 'ingredients_list', 'common_ingr']].head(10)

,code,product_name,ingredients_list,common_ingr
0,8901571010844,Sensodyne Repair & Protect,"[aroma, sodium saccharin, carbomer, glycerin, ...","[aroma, sodium saccharin, carbomer, glycerin, ..."
1,3094905000033,Répare & Protège,"[aroma, sodium saccharin, carbomer, glycerin, ...","[aroma, sodium saccharin, carbomer, glycerin, ..."
2,5054563155658,Repair & Protect,"[aroma, sodium saccharin, carbomer, glycerin, ...","[aroma, sodium saccharin, carbomer, glycerin, ..."
3,5054563006592,Sensodyne repair & protect,"[aroma, sodium saccharin, carbomer, glycerin, ...","[aroma, sodium saccharin, carbomer, glycerin, ..."
4,6001076192525,tooth,"[aroma, sodium saccharin, contains sodium fluo...","[aroma, sodium saccharin, carbomer, glycerin, ..."
5,5054563109743,Sensodyne sensibilidade e gengivas,"[aroma, sodium saccharin, carbomer, glycerin, ...","[aroma, sodium saccharin, carbomer, glycerin, ..."
6,5054563010278,Rapide Action Extra Fresh,"[aroma, sodium saccharin, carbomer, glycerin, ...","[aroma, sodium saccharin, carbomer, glycerin, ..."
7,05050499,Sensodyne Sensibilité & Gencives,"[aroma, sodium saccharin, carbomer, glycerin, ...","[aroma, sodium saccharin, carbomer, glycerin, ..."
8,5054563024558,Rapide Action,"[aroma, sodium saccharin, carbomer, glycerin, ...","[aroma, sodium saccharin, carbomer, glycerin, ..."
9,3094904751622,Rapide action,"[aroma, sodium saccharin, carbomer, glycerin, ...","[aroma, sodium saccharin, carbomer, glycerin, ..."

In [43]:
ing_sim_array[:10]

array([0.        , 0.        , 0.0625    , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.04166667, 0.05263158])

In [44]:
df_ing_candidates.head(10)

,code,product_name,macro_category,ingredients,ingredients_list,ing_sim,is_query,common_ingr
0,8901571010844,Sensodyne Repair & Protect,Other,"Aroma, Calcium Sodium Phosphosilicate, Carbome...","[aroma, sodium saccharin, carbomer, glycerin, ...",1.000000,True,"[aroma, sodium saccharin, carbomer, glycerin, ..."
1,3094905000033,Répare & Protège,Other,"Aroma, Calcium Sodium Phosphosilicate, Carbome...","[aroma, sodium saccharin, carbomer, glycerin, ...",0.916667,False,"[aroma, sodium saccharin, carbomer, glycerin, ..."
2,5054563155658,Repair & Protect,Other,"Aroma, Calcium Sodium Phosphosilicate, Carbome...","[aroma, sodium saccharin, carbomer, glycerin, ...",0.916667,False,"[aroma, sodium saccharin, carbomer, glycerin, ..."
3,5054563006592,Sensodyne repair & protect,Other,"Aroma, Calcium Sodium Phosphosilicate, Carbome...","[aroma, sodium saccharin, carbomer, glycerin, ...",0.916667,False,"[aroma, sodium saccharin, carbomer, glycerin, ..."
4,6001076192525,tooth,Other,"Aroma, Calcium Sodium Phosphosilicate, Carbome...","[aroma, sodium saccharin, contains sodium fluo...",0.846154,False,"[aroma, sodium saccharin, carbomer, glycerin, ..."
5,5054563109743,Sensodyne sensibilidade e gengivas,Other,"Aroma, Carbomer, Cocamidopropyl Betaine, Glyce...","[aroma, sodium saccharin, carbomer, glycerin, ...",0.733333,False,"[aroma, sodium saccharin, carbomer, glycerin, ..."
6,5054563010278,Rapide Action Extra Fresh,Other,"Aroma, Carbomer, Cocamidopropyl Betaine, Glyce...","[aroma, sodium saccharin, carbomer, glycerin, ...",0.666667,False,"[aroma, sodium saccharin, carbomer, glycerin, ..."
7,05050499,Sensodyne Sensibilité & Gencives,Other,"Aroma, Carbomer, Cocamidopropyl Betaine, Glyce...","[aroma, sodium saccharin, carbomer, glycerin, ...",0.666667,False,"[aroma, sodium saccharin, carbomer, glycerin, ..."
8,5054563024558,Rapide Action,Other,"Aroma, Carbomer, Cocamidopropyl Betaine, Glyce...","[aroma, sodium saccharin, carbomer, glycerin, ...",0.600000,False,"[aroma, sodium saccharin, carbomer, glycerin, ..."
9,3094904751622,Rapide action,Other,"Aroma, Carbomer, Cocamidopropyl Betaine, Glyce...","[aroma, sodium saccharin, carbomer, glycerin, ...",0.600000,False,"[aroma, sodium saccharin, carbomer, glycerin, ..."

**5. Indicizzazione su codice prodotto**

Costruzione nuovo DF: unione dei due dataframe sul codice prodotto al fine del calcolo della similarità finale.

In [45]:
df_ing= df_ing_candidates[['code', 'ing_sim']].copy()

df_brand = df_brand_candidates[['code']].copy()
df_brand['brand_sim'] = brand_sim_array

#allineo la similarità
df_merged = df_ing.merge(
    df_brand,
    on='code',
    how='inner'
)

In [46]:
#check per verificare che l'allineamento è corretto
assert len(df_merged) > 0
assert df_merged['code'].is_unique

df_merged.head()

            code   ing_sim  brand_sim
0  3094905000033  0.916667        0.7
1  5054563155658  0.916667        1.0
2  5054563006592  0.916667        1.0
3  5054563109743  0.733333        1.0
4  5054563010278  0.666667        1.0

**6. Calcolo della similarità finale**

Gli ingredienti hanno peso maggiore nel determinare il prodotto più simile (0.8). I brand hanno peso minore (0.2).

In [47]:
df_merged['final_similarity'] = (
    0.8 * df_merged['ing_sim'] +
    0.2 * df_merged['brand_sim']
)

**6. Costruzione dataframe per la visualizzazione del prodotto più simile**

In [49]:
query_product_name = (
    df.loc[df['code'] == query_id, 'product_name']
    .iloc[0]
)

ingredients_query = (
    df_ing_candidates['ingredients']
    .iloc[0]
)


risultato = pd.DataFrame({
    'query_product_id': query_id,
    'query_product_name': query_product_name,
    'recommended_product_id': df_merged['code'],
    'final_similarity_score': df_merged['final_similarity'],
    'common_ingredients': df_ing_candidates['common_ingr'],
    'ingredients_query': ingredients_query

})

#ordino i prodotti per suggerire il prodotto più simile
risultato = risultato.sort_values(
    by='final_similarity_score',
    ascending=False
).reset_index(drop=True)

risultato['rank'] = risultato.index + 1

# arricchimento informativo (nome, brand, segmento)
risultato = risultato.merge(
    df[['code', 'product_name', 'brand_name', 'brand_segment']],
    left_on='recommended_product_id',
    right_on='code',
    how='left'
).drop(columns='code')

risultato['num_common_ingredients'] = risultato['common_ingredients'].apply(
    lambda x: len(x) if isinstance(x, (list, set, tuple)) else len(str(x).split(','))
)

risultato = risultato[
    [
        'rank',
        'query_product_id',
        'query_product_name',
        'ingredients_query',
        'recommended_product_id',
        'product_name',
        'brand_name',
        'brand_segment',
        'common_ingredients',
        'num_common_ingredients',
        'final_similarity_score'
    ]
]



risultato.head(10)

,rank,query_product_id,query_product_name,ingredients_query,recommended_product_id,product_name,brand_name,brand_segment,common_ingredients,num_common_ingredients,final_similarity_score
0,1,8901571010844,sensodyne repair protect,"Aroma, Calcium Sodium Phosphosilicate, Carbome...",5054563006592,sensodyne repair protect,sensodyne,mass_market,"[aroma, sodium saccharin, carbomer, glycerin, ...",11,0.933333
1,2,8901571010844,sensodyne repair protect,"Aroma, Calcium Sodium Phosphosilicate, Carbome...",5054563155658,repair protect,sensodyne,mass_market,"[aroma, sodium saccharin, carbomer, glycerin, ...",11,0.933333
2,3,8901571010844,sensodyne repair protect,"Aroma, Calcium Sodium Phosphosilicate, Carbome...",3094905000033,repare protege,glaxosmithkline,mass_market,"[aroma, sodium saccharin, carbomer, glycerin, ...",12,0.873333
3,4,8901571010844,sensodyne repair protect,"Aroma, Calcium Sodium Phosphosilicate, Carbome...",5054563109743,sensodyne sensibilidade e gengivas,sensodyne,mass_market,"[aroma, sodium saccharin, carbomer, glycerin, ...",11,0.786667
4,5,8901571010844,sensodyne repair protect,"Aroma, Calcium Sodium Phosphosilicate, Carbome...",5054563010278,rapide action extra fresh,sensodyne,mass_market,"[aroma, sodium saccharin, carbomer, glycerin, ...",11,0.733333
5,6,8901571010844,sensodyne repair protect,"Aroma, Calcium Sodium Phosphosilicate, Carbome...",5054563024558,rapide action,sensodyne,mass_market,"[aroma, sodium saccharin, carbomer, glycerin, ...",10,0.680000
6,7,8901571010844,sensodyne repair protect,"Aroma, Calcium Sodium Phosphosilicate, Carbome...",3094904751622,rapide action,sensodyne,mass_market,"[aroma, sodium saccharin, carbomer, glycerin, ...",10,0.680000
7,8,8901571010844,sensodyne repair protect,"Aroma, Calcium Sodium Phosphosilicate, Carbome...",05050499,sensodyne sensibilite gencives,gsk,mass_market,"[aroma, sodium saccharin, carbomer, glycerin, ...",11,0.673333
8,9,8901571010844,sensodyne repair protect,"Aroma, Calcium Sodium Phosphosilicate, Carbome...",5054563049957,sensibilite et gencives,sensodyne,mass_market,"[aroma, sodium saccharin, carbomer, glycerin, ...",9,0.650000
9,10,8901571010844,sensodyne repair protect,"Aroma, Calcium Sodium Phosphosilicate, Carbome...",5054563256522,sensodyne expert protect rapide action,sensodyne,mass_market,"[aroma, sodium saccharin, carbomer, glycerin, ...",9,0.650000