#Sistema di raccomandazione
Il sistema implementa un approccio di raccomandazione one-time, evitando la costruzione di matrici di similarità NxN. Applica un filtro hard sulla categoria e combina una similarità basata su ingredienti con una funzione deterministica di brand e segmento, pesate rispettivamente 0.8 e 0.2.

In [7]:
import pandas as pd
import numpy as np

1) Importo il df e creo un nuovo df con le colonne d'interesse

In [9]:
df = pd.read_csv("brand_categoria.csv",dtype={"code": str})

df = df[['code', 'product_name','brand_name', 'brand_segment','macro_category']].copy()
df['code'] = df['code'].astype(str)
df['product_name'] = df['product_name'].astype(str)
df['brand_name'] = df['brand_name'].astype(str)
df['brand_segment'] = df['brand_segment'].astype(str)
df['macro_category'] = df['macro_category'].astype(str)


df.tail(30)

FileNotFoundError: [Errno 2] No such file or directory: 'brand_categoria.csv'

In [ ]:
df_ing = pd.read_csv("ingr_cat.csv",dtype={"code": str})


df_ing['code'] = df_ing['code'].astype(str)
df_ing['product_name'] = df_ing['product_name'].astype(str)
df_ing['macro_category'] = df_ing['macro_category'].astype(str)
df_ing['inci_name'] = df_ing['inci_name'].astype(str)

df_finale = (
    df_ing
    .groupby(['code', 'product_name', 'macro_category'])['inci_name']
    .apply(lambda lst: ", ".join(sorted(set(lst))))
    .reset_index()
    .rename(columns={'inci_name': 'ingredients'}))

df_finale.tail(20)

,code,product_name,macro_category,ingredients
15111,96121214,Powder soft anti perspirant,Other,"Alpha-Isomethyl Lonone, Aluminum Zirconium Tet..."
15112,96125694,REXONA Déodorant Homme Bille Anti Transpirant ...,Deodorants,"Alpha-Isomethyl Ionone, Aluminum Zirconium Tet..."
15113,96125748,Motionsense active shield,Other,"Alpha-Lsomethyl Lonone, Aluminum Chlorohydrate..."
15114,96130339,Dove zero original 50ml,Body_Care,"Alpha-Isomethyl Ionone, Benzyl Alcohol, Citric..."
15115,96132289,Axe Déodorant Anti Bactérien You Spray 100ml,Deodorants,"Alcohol Denat, Alpha-Isomethyl Ionone, Butane,..."
15116,96132876,Monsavon Déodorant Femme Spray Compressé Fleur...,Hygiene,"Alpha-Isomethyl Ionone, Benzyl Alcohol, Bht, B..."
15117,96132906,Monsavon Déodorant Femme Spray Compressé Grena...,Hygiene,"Alpha-Isomethyl Ionone, Benzyl Alcohol, Bht, B..."
15118,96134696,DOVE Déodorant Femme Spray Compressé Pierre d'...,Body_Care,"Alpha-Isomethyl Ionone, Benzyl Alcohol, Benzyl..."
15119,96148402,Monsavon Déodorant Femme Spray Compressé Vanil...,Hygiene,"Benzyl Alcohol, Bht, Butane, Butyrospermum Par..."
15120,96183281,sensodyne,Other,"Aroma, Carbomer, Cocamidopropyl Betaine, Die 7..."
15121,96190807,Clay Pomade,Other,"Bentonite, Ceteareth-20, Ethylhexyl Palmitate,..."
15122,9680150153491,nutri-extrême richesse,Other,"Alpha-Isomethyl Ionone, Benzyl Alcohol, Benzyl..."
15123,9700490730098,Allo,Other,Allo
15124,9767014005810,prêt plus,Other,"91717 Wassertruedingen, Water"
15125,9782253122111,Doliprane bebe,Makeup,"Acide Citrique Anhydre, Arme Orange, Arme Pch ..."
15126,9836763040011,Fragrance Free Conditioner,Hair_Care,"Behentrimonium Chloride, Cetearyl Alcohol, Cet..."
15127,9858406315515,Colgate plax,Hygiene,Colgate
15128,988010630504861790,curl therapy conditioner wash,Hair_Care,"Bambusa Vulgaris Shoot Extract, Capryliccapric..."
15129,9978135848778,Pigmento,Men_Care,"Decamethylcyclopentasiloxane, Ethylhexyl Palmi..."
15130,99941208,Zincodermil shampoo,Hair_Care,"20, Arctium Lappa Root Extract, Citric Acid, C..."

In [ ]:
#per la semplificazione della ricerca in fase di test, è una lista di "code" in comune tra i dataset
common_codes = set(df['code']).intersection(set(df_finale['code']))

print(f"Prodotti in df: {len(df)}")
print(f"Prodotti in df_finale: {len(df_finale)}")
print(f"Prodotti comuni: {len(common_codes)}")
common_codes

Prodotti in df: 31056
Prodotti in df_finale: 15131
Prodotti comuni: 12304

{'8001090102997',
 '3574661261065',
 '4005808246038',
 '3600542075091',
 '3560071132774',
 '8432225096735',
 '3257982124980',
 '4003573020051',
 '3600541291447',
 '3600522401032',
 '4058172938740',
 '6002413076119',
 '5028197823160',
 '3450970117739',
 '3153716003432',
 '0663350065558',
 '3600523399826',
 '8431876282061',
 '3600523583270',
 '8480000464170',
 '3250390448730',
 '8001090365255',
 '8717163651735',
 '8720181001857',
 '4010355505347',
 '8480000468161',
 '0878941001741',
 '4005808283804',
 '8717163732465',
 '8710908571596',
 '3614229376777',
 '4335619174795',
 '5420008514814',
 '3245678043844',
 '3560070337651',
 '3511720128303',
 '3600522448471',
 '4010355340450',
 '4006000132303',
 '9312657010013',
 '0634084471700',
 '2017017699996',
 '0697029421437',
 '8993137723756',
 '3478820044035',
 '3600541540262',
 '8412300836586',
 '8720181092763',
 '4021457606672',
 '0850005911395',
 '2000000002886',
 '6111273490154',
 '7640183490422',
 '3153716007966',
 '3662217011759',
 '3337875583589',
 '8902319040024',
 '4005808890576',
 '3245678704622',
 '3517360005509',
 '3600542130998',
 '3282779007504',
 '3610340026089',
 '3380810045277',
 '3549620005035',
 '4015400636649',
 '8717163699263',
 '3250391421763',
 '3400941631245',
 '3337872410338',
 '3058320002034',
 '3337875597449',
 '4103040019448',
 '3506770303015',
 '8710447285343',
 '3661434004704',
 '3574661617510',
 '3140100047875',
 '8718951131767',
 '3574661054780',
 '3596710523979',
 '4015100293135',
 '3401397163618',
 '8431876282085',
 '4067796002737',
 '3664696003065',
 '4894532923502',
 '5045498902158',
 '5060356734214',
 '6935743174876',
 '3600523543779',
 '3600524017729',
 '7791293048482',
 '8001841920931',
 '8717163997345',
 '4250587772173',
 '5400601006626',
 '3040690666015',
 '8720181297618',
 '2000000003668',
 '3282770023879',
 '3600531589387',
 '3574661065410',
 '7702018368693',
 '3596710387076',
 '4066447331202',
 '7730207079181',
 '3283021753156',
 '4015001007275',
 '20012984',
 '3215666800087',
 '8717644091777',
 '3600541887930',
 '3564700279007',
 '3661434002304',
 '0764302211068',
 '8480000236753',
 '8718951562158',
 '9328514001384',
 '7790010959803',
 '9316254017109',
 '4015001005455',
 '5054563086433',
 '3596206227794',
 '0829576020058',
 '3337875549493',
 '8718924879818',
 '7630028615516',
 '5748996064006',
 '7066307102949',
 '3283950020121',
 '8594071258160',
 '8717644256183',
 '8001090761187',
 '20007461',
 '8001090989932',
 '3181730272589',
 '3331849002908',
 '3596710524303',
 '8001120833693',
 '2000000005165',
 '3596710517145',
 '3256224359500',
 '3517360021127',
 '7340191139701',
 '7709522594839',
 '8435054684111',
 '3600550106541',
 '50096701',
 '3378872073673',
 '7640183490378',
 '4305615683300',
 '4607183282528',
 '3283950910903',
 '0899962000025',
 '8710522963494',
 '8422838118214',
 '4056489511571',
 '3560070924165',
 '6130793004214',
 '8717163629079',
 '3140100261325',
 '8720181086281',
 '6130601012172',
 '0827854013761',
 '8710908570315',
 '8720181077692',
 '3178040695771',
 '3564700863688',
 '4260437290139',
 '42354840',
 '8710847969744',
 '7611480007798',
 '3760205284823',
 '4066447384055',
 '8431876271461',
 '7340011315599',
 '8906136090859',
 '3600541827868',
 '8480000770073',
 '3367729021028',
 '3337875597210',
 '3401344502200',
 '4015000944038',
 '0752830779389',
 '8427483030058',
 '8480024551726',
 '3250392343118',
 '4056489294566',
 '3760209870121',
 '7898581082309',
 '3760368740754',
 '8718951254183',
 '8410412027045',
 '3564700718513',
 '3474630699533',
 '8431876271676',
 '8411047102558',
 '3245678042182',
 '3560070969227',
 '3770008167049',
 '3770022721036',
 '3560070630509',
 '0792850164000',
 '4021457615872',
 '4015600862640',
 '3401360114739',
 '3508240000271',
 '3401097676029',
 '7891150091153',
 '4305615629025',
 '3517360011364',
 '3125300000035',
 '3350031684722',
 '8710908843044',
 '0850502007775',
 '3560070158720',
 '9000101609288',
 '8054042630208',
 '5028197249298',
 '8718951066816',
 '3600542432757',
 '3600542565639',
 '3337875763790',
 '4058172623790',
 '0651986704897',
 '3245678674949',
 '3133200053129',
 '0745114970503',
 '7350121253452',
 '3222476085696',
 '3596710381289',
 '3600523939916',
 '5000262137006',
 '3401360114890',
 '3511720000005',
 '7340011429357',
 '4103040102744',
 '5901018021122',
 '8681171520737',
 '3760211480431',
 '3245678675007',
 '3014260095185',
 '8901030907449',
 '80512134',
 '8006540945162',
 '4316268522083',
 '8424818169506',
 '3600541883642',
 '3614272046283',
 '8718537598793',
 '0735745796115',
 '4015600718275',
 '3600550258776',
 '3600531537289',
 '3605975099676',
 '3700454223419',
 '7896512921789',
 '8718951087415',
 '0764302224044',
 '3401340799840',
 '3245678561799',
 '3517360013863',
 '3660297020425',
 '3770002220832',
 '7611916124501',
 '3600541436244',
 '8480000467874',
 '3760076654619',
 '3094900059791',
 '3245677725420',
 '3600540559197',
 '8710522440933',
 '5449750032940',
 '8718537373635',
 '3760226800095',
 '7630028609348',
 '42299943',
 '59082958',
 '3337875545822',
 '4084500736306',
 '8001280027284',
 '3600523640195',
 '6970734412070',
 '3350031977954',
 '3350031992612',
 '5900998006556',
 '3600550231922',
 '3574669909792',
 '4316268477697',
 '3600550964738',
 '3454606077657',
 '42204084',
 '5054186283004',
 '8001090863072',
 '8480000794277',
 '3178041327183',
 '5057753639303',
 '3600550815887',
 '0857584005170',
 '3760182264511',
 '7774904260466',
 '2299630305410',
 '5054563149954',
 '7624900123640',
 '3600523939718',
 '3564700278987',
 '8720181140372',
 '8006540687505',
 '3700211181327',
 '8431876273434',
 '3574661575209',
 '3564700279038',
 '3283950912617',
 '26023717',
 '8851111429035',
 '50077786',
 '4058172493133',
 '8712561772730',
 '8714789828558',
 '0608887042481',
 '7310610029050',
 '4016208854846',
 '8809093097100',
 '6260031029041',
 '8431876273410',
 '3600551033082',
 '4056489565086',
 '8430321719411',
 '3245678127339',
 '3337875537308',
 '3256224061199',
 '7640183490651',
 '5949067504456',
 '4800067642696',
 '3600522054085',
 '20055929',
 '3560070922208',
 '8718951315907',
 '0731882497021',
 '3760194657707',
 '59079330',
 '7501007528434',
 '7770108070597',
 '0615908431599',
 '9000101668834',
 '5054563093394',
 '8710522489871',
 '3600550199338',
 '8410757957717',
 '5412058146794',
 '7891150070318',
 '8001090786852',
 '3537090010086',
 '3600541599031',
 '3287570131014',
 '0875010001954',
 '3574661231358',
 '0665124561235',
 '0792850907577',
 '4005808236923',
 '5010123726621',
 '6130024166018',
 '8710447493939',
 '4017645046283',
 '3560070627950',
 '59013976',
 '3478820303453',
 '7332531093248',
 '7640183490279',
 '7391899845876',
 '7649991272015',
 '8710908571299',
 '5410076518425',
 '8718951311510',
 '8720289261542',
 '20855444',
 '3283950011006',
 '20317225',
 '8015700169096',
 '8480000449832',
 '8901288011004',
 '3700446410162',
 '8681715687520',
 '0850056671187',
 '5410091701857',
 '8719238033286',
 '4260486336543',
 '0628333101685',
 '4001638081870',
 '4086900105423',
 '5907813936340',
 '9339341017486',
 '8411126020674',
 '73123538',
 '8710847922633',
 '3286010022066',
 '3245678671139',
 '8480010177329',
 '4002448122432',
 '8720181077661',
 '9341104589130',
 '8806334355975',
 '4005900444554',
 '7898567750604',
 '0667536214730',
 '3337872412486',
 '3178041315791',
 '4305615307619',
 '7899706159272',
 '7640183490255',
 '8711700923354',
 '8719324667999',
 '3596710403936',
 '8718951315518',
 '0769915190731',
 '3574661319216',
 '7791293040127',
 '3700454222894',
 '8719497836574',
 '8710908555732',
 '8714789928920',
 '3466762095741',
 '4021457628537',
 '3040690666220',
 '3560070890514',
 '8712561456555',
 '3350033137264',
 '4305615610023',
 '8711700889803',
 '3596710536603',
 '3284410036607',
 '8720181368097',
 '3014230010262',
 '7332531095013',
 '8718951666306',
 '0634707505546',
 '7046110075487',
 '3058320048117',
 '3596206462874',
 '3596710534883',
 '93575300',
 '28335689',
 '3059944117951',
 '7391681038653',
 '4305615610344',
 '3014230022401',
 '3251241025599',
 '3415900030458',
 '3245678144732',
 '3245678599761',
 '3439600018424',
 '4005900570956',
 '0882381017996',
 '8710908832420',
 '7640183490026',
 '4008233144825',
 '3660005795300',
 '4021457647859',
 '8033447586518',
 '42246619',
 '7702006301480',
 '3574661287898',
 '3245678130759',
 '3461922010206',
 '5054563051592',
 '3346470613584',
 '4005900399427',
 '26023731',
 '4008233161334',
 '96086261',
 '96121214',
 '96111307',
 '4066447786460',
 '3600522774525',
 '8480000468147',
 '3059946162348',
 '8480000467652',
 '7290102259489',
 '3337875597333',
 '3614223736485',
 '3014230021589',
 '3760096760697',
 '8480000233882',
 '8594060454948',
 '3286010026378',
 '3245678104019',
 '8001280022036',
 '3574661065359',
 '8714789733166',
 '3145891165708',
 '3600521708729',
 '3178041321853',
 '6336435354635',
 '3283950911177',
 '4001638099271',
 '3568312000622',
 '7313272148213',
 '0850155008532',
 '5054563068545',
 '3600541887541',
 '8718951128279',
 '3054080004028',
 '3760100682472',
 '3574660623574',
 '4005900546036',
 '8901030904486',
 '8005892347020',
 '4010355253798',
 '7310614024525',
 '8001090101341',
 '8718951115446',
 '8001090346988',
 '8710847955730',
 '3478820015899',
 '3760099591496',
 '0681131039130',
 '8710847935893',
 '3511728094006',
 '3660005713816',
 '3596710392391',
 '3596710524006',
 '8006540017166',
 '4021457645084',
 '3474393011085',
 '8410236008343',
 '3264680003578',
 '8710908744884',
 '7612449131059',
 '4004704104305',
 '3450270025543',
 '4894532923489',
 '8908003338255',
 '3564700632444',
 '0852569003561',
 '3440815112791',
 '3760265840939',
 '3564700788981',
 '3600522499725',
 '0681131136389',
 '0792850897687',
 '0666151010734',
 '2000000001059',
 '3010351730270',
 '8714789978390',
 '4005808129447',
 '3538396704105',
 '8436027342250',
 '3140100143089',
 '8004395000036',
 '4045612005537',
 '3222473018307',
 '3600550166545',
 '4021457614189',
 '3433422408159',
 '4010355559036',
 '3600550300628',
 '3600522016229',
 '4084500979208',
 '3600530746613',
 '3600522594277',
 '3574660348071',
 '3600523735839',
 '3560070902552',
 '4005900639523',
 '8712561344074',
 '8718951321762',
 '8002110383709',
 '3251241041667',
 '3596710520565',
 '4305615754635',
 '4770001333891',
 '3380380072710',
 '8720181140365',
 '3662076049146',
 '3337875548519',
 '5017634238506',
 '20179069',
 '3600541237476',
 '3306660849100',
 '3564700864678',
 '8017331073124',
 '3470320400380',
 '5903416015475',
 '3415900031486',
 '8682232501245',
 '96095027',
 '4015000971881',
 '4025089079767',
 '6716197317527',
 '0687735305046',
 '3430750793537',
 '0714847735489',
 '7702018453030',
 '4010355966100',
 '3600550234558',
 '14267192',
 '4058172488177',
 '8712566550159',
 '8718951249950',
 '3600550578041',
 '3760075070861',
 '3760162120561',
 '3701124800220',
 '3610340634185',
 '2000000152357',
 '3600523586349',
 '5201109623632',
 '8712561924221',
 '3251241016375',
 '8714789554372',
 '8719281075912',
 '3662217003891',
 '4010355347329',
 '4005900679291',
 '3178040208148',
 '8411047143056',
 '3054080006381',
 '3178040622326',
 '3245678599730',
 '4084500495982',
 '7509546054650',
 '8723300710807',
 '5000101193620',
 '3350033936652',
 '0870929002665',
 '5410091755317',
 '3760214630208',
 '8437014661880',
 '8470001780263',
 '2000000001062',
 '6920354822438',
 '7610108059461',
 '3504105029289',
 '5060322952376',
 '3014230000201',
 '4005900388490',
 '8710522420713',
 '3222475131356',
 '8712561484121',
 '3600521730645',
 '3257983361964',
 '3306360022476',
 '8720181059100',
 '8720181075476',
 '5060144644978',
 '5177257775489',
 '3760099593681',
 '0695652145638',
 '3178048242564',
 '3600550996036',
 '4084200771904',
 '3660005648194',
 '5054563104328',
 '8809414192170',
 '0863765000087',
 '3600541574083',
 '3401560062816',
 '0821055050297',
 '42242109',
 '3337872410208',
 '3401564695546',
 '3600550564044',
 '3489940070538',
 '5059018197375',
 '3058320020014',
 '3245678139516',
 '8714789113227',
 '3250391292790',
 '4010355216229',
 '3760099593544',
 '3600550808773',
 '4017645028579',
 '20172756',
 '3489940049367',
 '3141380052818',
 '3770001492001',
 '59083023',
 '8690506473860',
 '3770013899003',
 '8717163742815',
 '3560070956784',
 '3489940068085',
 '3600541738508',
 '7350048801873',
 '3245678704561',
 '7310610017590',
 '8718951197060',
 '8714789357935',
 '4021457619306',
 '9319871000622',
 '9005800261041',
 '4262391990025',
 '8002410033670',
 '30175259',
 '4058172266768',
 '5054563049063',
 '3337875398961',
 '3564700667866',
 '42345060',
 '0640509040147',
 '4260307638207',
 '3245678033081',
 '3574660085587',
 '4005808668649',
 '3466762106225',
 '3560070911349',
 '3600523611928',
 '3770004599172',
 '3400932331536',
 '5037156228144',
 '3549621011677',
 '7596211001033',
 '3286010022059',
 '50120000',
 '5000231050879',
 '3600550979367',
 '3250392228415',
 '40133034',
 '7805000311346',
 '3245678141281',
 '3215662980011',
 '3263855778518',
 '3600523972074',
 '2200281300792',
 '4305615572901',
 '4603014004437',
 '7610108024612',
 '8712561397759',
 '3564700658574',
 '3760257885115',
 '3614270429835',
 '3600542131193',
 '3600522365969',
 '40883113',
 '0898220003273',
 '3489941049762',
 '3600550288292',
 '3600542159654',
 '3504105002916',
 '3600522992455',
 '4316268718165',
 '3250391503544',
 '3596710386741',
 '8402001005558',
 '07924316',
 '0626232115031',
 '3537090016422',
 '8718951399747',
 '4056489368182',
 '4260437290016',
 '3380380083372',
 '08298214',
 '5000101514289',
 '3245678152584',
 '8718951131682',
 '3094900059722',
 '0735379340012',
 '3017563120998',
 '3564700701058',
 '5943001101053',
 '4013162027347',
 '8712561194365',
 '7319470058361',
 '8720181077708',
 '3661596831071',
 '5099821001421',
 '3564700877739',
 '5060686200113',
 '0681131071246',
 '3522931032051',
 '3564700714409',
 '3600523351244',
 '3274872280502',
 '3574661213729',
 '4806575478833',
 '8480000424464',
 '4021457614240',
 '8718951087521',
 '3516170022751',
 '7640183490675',
 '8480000777492',
 '48033459',
 '3596202561939',
 '0855275007106',
 '3595890234552',
 '3245678667163',
 '3010351750414',
 '3181734189395',
 '4058172774942',
 '3058325689322',
 '7310181582190',
 '7707178030244',
 '4005808848249',
 '0794437275680',
 '3567730300178',
 '3600541734722',
 '3574661008516',
 '27044759',
 '4017645016668',
 '3600541805880',
 '2000000000659',
 '0817891025254',
 '0667888306824',
 '4005808678747',
 '0719346218429',
 '3378872116189',
 '3266191023083',
 '5017174118108',
 '7898212282924',
 '4029753168313',
 '3560070882090',
 '3564700279021',
 '3245678674888',
 '3245678060995',
 '5000101189760',
 '5056004319315',
 '3286010022042',
 '5765228836637',
 '3517360017267',
 '8410276225601',
 '3401396680017',
 '3256223818497',
 '20250898',
 '3517360012415',
 '3700479107206',
 '4005900491046',
 '0895499714305',
 '4021457620005',
 '3574660711332',
 '3700599201860',
 '7702433291200',
 '6222019612218',
 '0810006942477',
 '30173156',
 '8712561617901',
 '8710908455599',
 '3401399372926',
 '3245678144794',
 '4008268016821',
 '4001638095556',
 '8294732983478',
 '8718114613994',
 '3600531584696',
 '3251241035376',
 '3256222740577',
 '5420008509148',
 '3661596982216',
 '4013891804462',
 '3181730117880',
 '3518646126970',
 '4013474107300',
 '3600550560107',
 '4002448051701',
 '3770013219047',
 '8410436233132',
 '3700216252688',
 '8710447442487',
 '3596710369928',
 '4056489525882',
 '4013891817783',
 '5028197890278',
 '8901030734168',
 '5907502687898',
 '8718951193796',
 '4010355409270',
 '3401347938594',
 '8402001014123',
 '6001886521021',
 '3600522471172',
 '3245678674871',
 '8710447346167',
 '3331840550002',
 '7500312020824',
 '3605972154842',
 '20057060',
 '3600523591831',
 '7311043009695',
 '8710447375105',
 '3600522108108',
 '4005900274861',
 '3245678130728',
 '3245678671153',
 '3595895323916',
 '2000000002529',
 '4003583176298',
 '7630019901741',
 '3266140060381',
 '7791293022598',
 '8717644598849',
 '0745114958068',
 '4388860244786',
 '4607945640399',
 '3282770073355',
 '4056489235972',
 '8001090098054',
 '8051739111903',
 '8033564686856',
 '5060571720528',
 '8431876238082',
 '3263855750729',
 '3245678127377',
 '0810074692076',
 '4894532923519',
 '8008970056593',
 '6281006409644',
 '7322540928525',
 '3478820035866',
 '0603084543854',
 '3346029401808',
 '4010355422743',
 '4021457647132',
 '8938510049191',
 '3245678599617',
 '4017512150457',
 '3600523899821',
 '3245678622902',
 '8711700543613',
 '4311501657508',
 '3245678599723',
 '8719326786568',
 '8712561631112',
 '8714789880518',
 '3052503030777',
 '3564700840719',
 '8719134155617',
 '4005900217936',
 '3245678045718',
 '3600540809407',
 '4894532923526',
 '3600523215553',
 '5400141700244',
 '8710908755552',
 '0773602657070',
 '4054495000614',
 '5901887036623',
 '3549620005080',
 '3250391906611',
 '6111255522460',
 '7640183490323',
 '8470007600176',
 '3600522356868',
 '3600540989253',
 '3600550363234',
 '3564700863442',
 '3059944117050',
 '3760324842034',
 '9000101591460',
 '4064666301945',
 '4052136005202',
 '80808756',
 '3215660760127',
 '3263855909714',
 '3160928965342',
 '7640163065473',
 '8001090094148',
 '0636874222509',
 '8712561484398',
 '3596209656003',
 '2528318287336',
 '3600523232482',
 '3257982125000',
 '3251248047341',
 '0815413023405',
 '2000000152355',
 '3504105036751',
 '3593290021895',
 '3600541237629',
 '0812154030068',
 '0689551299240',
 '5034843001202',
 '8710908650208',
 '6922275510043',
 '3600523277520',
 '3700599201099',
 '7702433292535',
 '0792850259997',
 '8720181077722',
 '3256224359241',
 '3251248046047',
 '4005800137068',
 '3245677725475',
 '7509546680750',
 '8711600420281',
 '3401597183256',
 '4066447434040',
 '3383482307711',
 '6223000659243',
 '8718951156111',
 '20825430',
 '3253581660508',
 '0811913015209',
 '3560070527175',
 '3245678612507',
 '4058172784651',
 '3596710544189',
 '7506078955035',
 '7611841701723',
 '9327693006920',
 '3181730331552',
 ...}

**2. Assegnazione pesi ai brand_segment.**

Il sistema di suggerimento tiene conto del segmento di mercato e pesa la similarità in base ad esso.
Prodotti dello stesso segmento avranno peso maggiore.

In [ ]:
SEGMENT_SIMILARITY = {
    ('middle', 'middle'): 0.7,
    ('mass_market', 'mass_market'): 0.7,
    ('luxury', 'luxury'): 0.7,

    ('mass_market', 'middle'): 0.5,
    ('middle', 'mass_market'): 0.5,

    ('mass_market', 'luxury'): 0.3,
    ('luxury', 'mass_market'): 0.3,

    ('middle', 'luxury'): 0.5,
    ('luxury', 'middle'): 0.5
}

**3. Creazione dell'array di similarità 1xK.**

Per il brand non uso una cosine similarity, ma una funzione deterministica basata su regole di business che tengono conto sia dell’identità del brand sia del segmento di mercato.

Il sistema applica un hard filter sulla categoria per ridurre lo spazio di ricerca e garantire coerenza semantica, e successivamente calcola una similarità pesata basata su ingredienti e su regole di brand e segmento.

In [ ]:
def brand_segment_similarity_1xK(
    query_product_id,
    df,
    category_col='macro_category',
    segment_col='brand_segment'
):
    query_product_id = str(query_product_id)

    if query_product_id not in df['code'].values:
        raise ValueError("Codice prodotto non trovato")

    query_row = df[df['code'] == query_product_id].iloc[0]
    query_category = query_row[category_col]
    query_brand = query_row['brand_name']
    query_segment = query_row[segment_col]
    query_product_name = query_row['product_name']  # ← AGGIUNTA

    # Filtro hard: stessa categoria -> ricerca tra prodotti della stessa categoria
    df_filtered = df[df[category_col] == query_category].copy()
    df_filtered = df_filtered[df_filtered['code'] != query_product_id]
    #filtro per evitare che restituisca lo stesso prodotto
    df_filtered['query_brand_name'] = query_brand
    df_filtered['query_product_name'] = query_product_name

    similarities = []

    for _, row in df_filtered.iterrows():
        if row['brand_name'] == query_brand:
            similarities.append(1.0)#se il prodotto appartiene allo stesso brand avrà similarità massima
        else:
            pair = (query_segment, row[segment_col]) #altrimenti considera il segmento di mercato
            similarities.append(SEGMENT_SIMILARITY.get(pair, 0.0))
    df_filtered['similarity'] = similarities
    return np.array(similarities), df_filtered

4. Applicazione della funzione e creazione dell'aray one-time a partire dal prodotto

In [ ]:
query_id = input('Inserisci il codice del prodotto: ')

brand_sim = brand_segment_similarity_1xK(query_id, df)
#non ottengo una matrice di similarità NXN, ma un array 1xK:
#cioè la similarità del prodotto query rispetto a tutti gli altri prodotti della stessa categoria



#brand_sim è una tupla: il primo elemento è l'array 1xK, il secondo elemento è il dataframe con i prodotti candidati
#brand_sim == (similarity_array, df_filtered).
#la tupla serve a sapere a quali prodotti mi riferisco
brand_sim_array, df_brand_candidates = brand_sim

Inserisci il codice del prodotto: 3245678612507

In [ ]:
brand_sim_array[:10] #vedo i primi dieci valori di similarità

array([0.5, 0.5, 0.5, 0.7, 0.7, 0.7, 0.7, 0.5, 0.7, 0.5])

In [ ]:
df_brand_candidates = df_brand_candidates[[
    'code',
    'query_product_name',
    'query_brand_name',
    'product_name',
    'brand_name',
    'brand_segment',
    'macro_category',
    'similarity'
]]

In [ ]:
df_brand_candidates.sort_values('similarity', ascending= False).head(10) #vedo i primi dieci candidati

,code,query_product_name,query_brand_name,product_name,brand_name,brand_segment,macro_category,similarity
7237,3245678612491,deodorant power 24h,cosmia,deodorant energy 24h,cosmia,middle,Deodorants,1.0
7235,3596710509287,deodorant power 24h,cosmia,deodorant,cosmia,middle,Deodorants,1.0
7247,3245678612682,deodorant power 24h,cosmia,deodorant voluptuous time,cosmia,middle,Deodorants,1.0
7254,3245678612415,deodorant power 24h,cosmia,deodorant instant voluptueux,cosmia,middle,Deodorants,1.0
7260,3245678612743,deodorant power 24h,cosmia,deodorant fleurs blanches 24h,cosmia,middle,Deodorants,1.0
7261,3245678612729,deodorant power 24h,cosmia,deodorant vanille,cosmia,middle,Deodorants,1.0
7232,3245678612439,deodorant power 24h,cosmia,deodorant vanille,cosmia,middle,Deodorants,1.0
7231,3245678612422,deodorant power 24h,cosmia,deodorant grenade,cosmia,middle,Deodorants,1.0
7090,3245678104026,deodorant power 24h,cosmia,deodorant,cosmia,middle,Deodorants,1.0
7057,3245677725475,deodorant power 24h,cosmia,deodorant compresse,cosmia,middle,Deodorants,1.0

5. Con questa funzione si trovano i prodotti più simili a un prodotto dato, guardando solo gli ingredienti. Prima limita il confronto ai prodotti della stessa categoria, così il confronto ha senso.
Poi confronta gli ingredienti del prodotto scelto con quelli degli altri e dice quanto si assomigliano, usando un punteggio numerico.

In [ ]:
#pulizia per esclusione ingredienti che potrebbero compromettere il corretto
#calcolo della similarità
EXCLUDE_INGREDIENTS = {
    'aqua', 'water', 'parfum', 'fragrance',
    'ci', 'color', 'colour',
    'sodium chloride'
}

def clean_ingredients(ing_string):
    ing = [
        i.strip().lower()
        for i in ing_string.split(',')
        if len(i.strip()) > 2
    ]
    ing = [
        i for i in ing
        if not any(x in i for x in EXCLUDE_INGREDIENTS)
        and not i.startswith('ci ')
    ]
    return list(set(ing))

In [ ]:
df_finale['ingredients_list'] = df_finale['ingredients'].apply(clean_ingredients)

df_finale[['ingredients', 'ingredients_list']].head(10)

,ingredients,ingredients_list
0,"Arnica Montana, Avoid Contact With Eyes, Burit...","[arnica montana, avoid contact with eyes, toco..."
1,Oil,[oil]
2,"Added Sugarss, Colorings, Cr 6Ad, Croydon, Lac...","[preservatives, cr 6ad, croydon, lactose, adde..."
3,Oil,[oil]
4,"Lilium Candidum Flower Extract, Oil","[oil, lilium candidum flower extract]"
5,"Allantoin, Aloe Barbadensis Leaf Juice, Benzoi...","[glycerin, phenoxyethanol, hydroxyethyl cellul..."
6,"Coco-Glucoside, Decyl Glucoside, Glycerin, Gly...","[glycerin, glyceryl oleate, sodium cocoyl glut..."
7,Lawsonia Inermis Leaf Powder,[lawsonia inermis leaf powder]
8,Natural Calcium Bentonite Clay,[]
9,"Cellulose Gum, Citric Acid, Cocamidopropyl Bet...","[glycerin, xanthan gum, cellulose gum, tetraso..."

In [ ]:
def jaccard_similarity(set_a, set_b):
    if not set_a or not set_b:
        return 0.0
    return len(set_a & set_b) / len(set_a | set_b)

In [ ]:
def ingredient_similarity_1xK(
    query_product_id,
    df_finale,
    category_col='macro_category'
):
    query_product_id = str(query_product_id)

    if query_product_id not in df_finale['code'].values:
        raise ValueError("Codice prodotto non trovato")

    query_row = df_finale[df_finale['code'] == query_product_id].iloc[0]
    query_category = query_row[category_col]
    query_ing = set(query_row['ingredients_list'])

    # Filtro hard: stessa categoria
    df_filtered = df_finale[df_finale[category_col] == query_category].copy()
    df_filtered = df_filtered[df_filtered['code'] != query_product_id]



    print(f"Trovati {len(df_filtered)} prodotti nella stessa categoria")

    similarities = []

    for _, row in df_filtered.iterrows():
        sim = jaccard_similarity(
            query_ing,
            set(row['ingredients_list'])
        )
        similarities.append(sim)

    return np.array(similarities), df_filtered

In [ ]:
ing_sim_array, df_ing_candidates = ingredient_similarity_1xK(query_id, df_finale)

ing_sim_array[:10]

Trovati 587 prodotti nella stessa categoria

array([0.04      , 0.08333333, 0.        , 0.07692308, 0.08333333,
       0.08333333, 0.        , 0.        , 0.        , 0.11111111])

In [ ]:
#aggiunta similarità e is_query per vedere quali sono i prod raccomandati e
#qual è il prodotto originale cercato
df_ing_candidates_temp = df_ing_candidates[df_ing_candidates['code'] != query_id].copy()
df_ing_candidates_temp['ing_sim'] = ing_sim_array
df_ing_candidates_temp['is_query'] = False
df_ing_candidates_temp = df_ing_candidates_temp.sort_values(by='ing_sim', ascending=False).reset_index(drop=True)


df_query_ing = df_finale[df_finale['code'] == query_id].copy()
df_query_ing['ing_sim'] = 1.0        # similarità massima con se stesso
df_query_ing['is_query'] = True

df_ing_candidates = pd.concat(
    [df_query_ing, df_ing_candidates_temp],
    ignore_index=True
)

df_ing_candidates.head(10)

,code,product_name,macro_category,ingredients,ingredients_list,ing_sim,is_query
0,3245678612507,Déodorant power 24h,Deodorants,"1, 2-Hexanediol, Alcohol Denat, Caprylyl Glyco...","[sodium hydroxide, oil, 2-hexanediol, hydroxye...",1.000000,True
1,3263855884592,Déobille 48h,Deodorants,"Alcohol Denat, Aluminum Chlorohydrate, Citric ...","[sodium hydroxide, aluminum chlorohydrate, oil...",0.444444,False
2,3245678612491,Déodorant Energy 24h,Deodorants,"Alcohol Denat, Allantoin, Citric Acid, Fragran...","[sodium hydroxide, ppg-26-buteth-26, oil, prop...",0.400000,False
3,4005808741601,Déodorant bille,Deodorants,"Alcohol Denat, Aluminum Chlorohydrate, Citric ...","[geraniol, aluminum chlorohydrate, oil, peg-8,...",0.300000,False
4,42349655,Cool Kick deodorant,Deodorants,"Alcohol Denat, Aluminum Chlorohydrate, Citric ...","[geraniol, aluminum chlorohydrate, oil, peg-8,...",0.300000,False
5,42419440,Nivea Deodorant Natural Balance mit bio aloe vera,Deodorants,"Alcohol Denat, Fragrance, Glycerin, Hydroxyeth...","[polyglyceryl-2-caprate, glycerin, hydroxyethy...",0.250000,False
6,4066447365320,Softflower Deodorant,Deodorants,"Alcohol Denat, Benzyl Alcohol, Benzyl Salicyla...","[sodium hydroxide, geraniol, limonene, polygly...",0.250000,False
7,8029041122153,defence deo,Deodorants,"Alcohol Denat, Aluminum Chlorohydrate, Capryly...","[glycerin, lactate, aluminum chlorohydrate, al...",0.222222,False
8,3337871310783,Déodorant Fraîcheur Extrême 24h,Deodorants,"Alcohol Denat, Code Fil C437241, Dipropylene G...","[sodium hydroxide, dipropylene glycol, code fi...",0.222222,False
9,3560070902552,Ocean Deo Stick,Deodorants,"Ci 15985, Ci 42053, Ethylhexylglycerin, Fragra...","[glycerin, sodium hydroxide, tocopherol, oil, ...",0.200000,False

In [ ]:
query_product_ingredients = set(
    df_finale[df_finale['code'] == query_id]['ingredients_list'].iloc[0]
)

def get_common_ingredients(candidate_ingredients):
    return list(query_product_ingredients.intersection(set(candidate_ingredients)))

df_ing_candidates['common_ingr'] = df_ing_candidates['ingredients_list'].apply(get_common_ingredients)

df_ing_candidates[['code', 'product_name', 'ingredients_list', 'common_ingr']].head(10)

,code,product_name,ingredients_list,common_ingr
0,3245678612507,Déodorant power 24h,"[sodium hydroxide, oil, 2-hexanediol, hydroxye...","[sodium hydroxide, oil, 2-hexanediol, hydroxye..."
1,3263855884592,Déobille 48h,"[sodium hydroxide, aluminum chlorohydrate, oil...","[sodium hydroxide, alcohol denat, hydroxyethyl..."
2,3245678612491,Déodorant Energy 24h,"[sodium hydroxide, ppg-26-buteth-26, oil, prop...","[sodium hydroxide, alcohol denat, hydroxyethyl..."
3,4005808741601,Déodorant bille,"[geraniol, aluminum chlorohydrate, oil, peg-8,...","[alcohol denat, hydroxyethylcellulose, oil]"
4,42349655,Cool Kick deodorant,"[geraniol, aluminum chlorohydrate, oil, peg-8,...","[alcohol denat, hydroxyethylcellulose, oil]"
5,42419440,Nivea Deodorant Natural Balance mit bio aloe vera,"[polyglyceryl-2-caprate, glycerin, hydroxyethy...","[hydroxyethylcellulose, alcohol denat]"
6,4066447365320,Softflower Deodorant,"[sodium hydroxide, geraniol, limonene, polygly...","[sodium hydroxide, hydroxyethylcellulose, alco..."
7,8029041122153,defence deo,"[glycerin, lactate, aluminum chlorohydrate, al...","[alcohol denat, caprylyl glycol]"
8,3337871310783,Déodorant Fraîcheur Extrême 24h,"[sodium hydroxide, dipropylene glycol, code fi...","[sodium hydroxide, alcohol denat]"
9,3560070902552,Ocean Deo Stick,"[glycerin, sodium hydroxide, tocopherol, oil, ...","[sodium hydroxide, oil]"

In [ ]:
ing_sim_array[:10]

array([0.04      , 0.08333333, 0.        , 0.07692308, 0.08333333,
       0.08333333, 0.        , 0.        , 0.        , 0.11111111])

In [ ]:
df_ing_candidates.head(10)

,code,product_name,macro_category,ingredients,ingredients_list,ing_sim,is_query,common_ingr
0,3245678612507,Déodorant power 24h,Deodorants,"1, 2-Hexanediol, Alcohol Denat, Caprylyl Glyco...","[sodium hydroxide, oil, 2-hexanediol, hydroxye...",1.000000,True,"[sodium hydroxide, oil, 2-hexanediol, hydroxye..."
1,3263855884592,Déobille 48h,Deodorants,"Alcohol Denat, Aluminum Chlorohydrate, Citric ...","[sodium hydroxide, aluminum chlorohydrate, oil...",0.444444,False,"[sodium hydroxide, alcohol denat, hydroxyethyl..."
2,3245678612491,Déodorant Energy 24h,Deodorants,"Alcohol Denat, Allantoin, Citric Acid, Fragran...","[sodium hydroxide, ppg-26-buteth-26, oil, prop...",0.400000,False,"[sodium hydroxide, alcohol denat, hydroxyethyl..."
3,4005808741601,Déodorant bille,Deodorants,"Alcohol Denat, Aluminum Chlorohydrate, Citric ...","[geraniol, aluminum chlorohydrate, oil, peg-8,...",0.300000,False,"[alcohol denat, hydroxyethylcellulose, oil]"
4,42349655,Cool Kick deodorant,Deodorants,"Alcohol Denat, Aluminum Chlorohydrate, Citric ...","[geraniol, aluminum chlorohydrate, oil, peg-8,...",0.300000,False,"[alcohol denat, hydroxyethylcellulose, oil]"
5,42419440,Nivea Deodorant Natural Balance mit bio aloe vera,Deodorants,"Alcohol Denat, Fragrance, Glycerin, Hydroxyeth...","[polyglyceryl-2-caprate, glycerin, hydroxyethy...",0.250000,False,"[hydroxyethylcellulose, alcohol denat]"
6,4066447365320,Softflower Deodorant,Deodorants,"Alcohol Denat, Benzyl Alcohol, Benzyl Salicyla...","[sodium hydroxide, geraniol, limonene, polygly...",0.250000,False,"[sodium hydroxide, hydroxyethylcellulose, alco..."
7,8029041122153,defence deo,Deodorants,"Alcohol Denat, Aluminum Chlorohydrate, Capryly...","[glycerin, lactate, aluminum chlorohydrate, al...",0.222222,False,"[alcohol denat, caprylyl glycol]"
8,3337871310783,Déodorant Fraîcheur Extrême 24h,Deodorants,"Alcohol Denat, Code Fil C437241, Dipropylene G...","[sodium hydroxide, dipropylene glycol, code fi...",0.222222,False,"[sodium hydroxide, alcohol denat]"
9,3560070902552,Ocean Deo Stick,Deodorants,"Ci 15985, Ci 42053, Ethylhexylglycerin, Fragra...","[glycerin, sodium hydroxide, tocopherol, oil, ...",0.200000,False,"[sodium hydroxide, oil]"

**5. Indicizzazione su codice prodotto**

Costruzione nuovo DF: unione dei due dataframe sul codice prodotto al fine del calcolo della similarità finale.

In [ ]:
df_ing= df_ing_candidates[['code', 'ing_sim']].copy()

df_brand = df_brand_candidates[['code']].copy()
df_brand['brand_sim'] = brand_sim_array

#allineo la similarità
df_merged = df_ing.merge(
    df_brand,
    on='code',
    how='inner'
)

In [ ]:
#check per verificare che l'allineamento è corretto
assert len(df_merged) > 0
assert df_merged['code'].is_unique

df_merged.head()

            code   ing_sim  brand_sim
0  3263855884592  0.444444        0.5
1  3245678612491  0.400000        1.0
2  4005808741601  0.300000        0.5
3       42349655  0.300000        0.5
4       42419440  0.250000        0.5

**6. Calcolo della similarità finale**

Gli ingredienti hanno peso maggiore nel determinare il prodotto più simile (0.8). I brand hanno peso minore (0.2).

In [ ]:
df_merged['final_similarity'] = (
    0.8 * df_merged['ing_sim'] +
    0.2 * df_merged['brand_sim']
)

**6. Costruzione dataframe per la visualizzazione del prodotto più simile**

In [ ]:
query_product_name = (
    df.loc[df['code'] == query_id, 'product_name']
    .iloc[0]
)
risultato = pd.DataFrame({
    'query_product_id': query_id,
    'query_product_name': query_product_name,
    'recommended_product_id': df_merged['code'],
    'final_similarity_score': df_merged['final_similarity'],
    'common_ingredients': df_ing_candidates['common_ingr'],
    'ingredients_query': df_ing_candidates['ingredients']

})

#ordino i prodotti per suggerire il prodotto più simile
risultato = risultato.sort_values(
    by='final_similarity_score',
    ascending=False
).reset_index(drop=True)

risultato['rank'] = risultato.index + 1

# arricchimento informativo (nome, brand, segmento)
risultato = risultato.merge(
    df[['code', 'product_name', 'brand_name', 'brand_segment']],
    left_on='recommended_product_id',
    right_on='code',
    how='left'
).drop(columns='code')

risultato = risultato[
    [
        'rank',
        'query_product_id',
        'query_product_name',
        'ingredients_query',
        'recommended_product_id',
        'product_name',
        'brand_name',
        'brand_segment',
        'common_ingredients',
        'final_similarity_score'
    ]
]

risultato.head(10)

,rank,query_product_id,query_product_name,ingredients_query,recommended_product_id,product_name,brand_name,brand_segment,common_ingredients,final_similarity_score
0,1,3245678612507,deodorant power 24h,"Alcohol Denat, Aluminum Chlorohydrate, Citric ...",3245678612491,deodorant energy 24h,cosmia,middle,"[sodium hydroxide, alcohol denat, hydroxyethyl...",0.520000
1,2,3245678612507,deodorant power 24h,"1, 2-Hexanediol, Alcohol Denat, Caprylyl Glyco...",3263855884592,deobille 48h,sooa,luxury,"[sodium hydroxide, oil, 2-hexanediol, hydroxye...",0.455556
2,3,3245678612507,deodorant power 24h,"Alcohol Denat, Allantoin, Citric Acid, Fragran...",4005808741601,deodorant bille,nivea men,mass_market,"[sodium hydroxide, alcohol denat, hydroxyethyl...",0.340000
3,4,3245678612507,deodorant power 24h,"Alcohol Denat, Aluminum Chlorohydrate, Citric ...",42349655,cool kick deodorant,nivea men,mass_market,"[alcohol denat, hydroxyethylcellulose, oil]",0.340000
4,5,3245678612507,deodorant power 24h,"Alcohol Denat, Citric Acid, Disodium Phosphate...",3245678612439,deodorant vanille,cosmia,middle,"[alcohol denat, hydroxyethylcellulose, oil]",0.333333
5,6,3245678612507,deodorant power 24h,"Arachidic Acid, Butyloctanoic Acid, Distarch P...",3245677725437,deodorant,cosmia,middle,"[sodium hydroxide, oil]",0.333333
6,7,3245678612507,deodorant power 24h,"Alcohol Denat, Aluminum Chlorohydrate, Citric ...",42419440,nivea deodorant natural balance mit bio aloe vera,nivea,mass_market,"[alcohol denat, hydroxyethylcellulose, oil]",0.300000
7,8,3245678612507,deodorant power 24h,"Alcohol Denat, Fragrance, Glycerin, Hydroxyeth...",4066447365320,softflower deodorant,dm balea,mass_market,"[hydroxyethylcellulose, alcohol denat]",0.300000
8,9,3245678612507,deodorant power 24h,"Arachidic Acid, Bht, Caprylyl Glycol, Citric A...",3245678612422,deodorant grenade,cosmia,middle,"[oil, caprylyl glycol]",0.294118
9,10,3245678612507,deodorant power 24h,"2-Methyl 5-Cyclohexylpentanol, Acetic Acid, Ca...",3245677725475,deodorant compresse,cosmia,middle,"[oil, caprylyl glycol]",0.280000